### ISSUE TITLE
It looks very nice. 

### ISSUE THREAD

**Issue by PythonLinks** [xysun/pychat#2]
Maybe it is the only Python Chat server which supports multiple rooms. 

I would like to spend more time with it, but first I have to ask 
what is the license?

And wehre are you located?  May I add you to my map of open source python projects. 
PythonLinks.info

Warm Regards
Chris

**Comment by xysun** [comment]
Hi -- I just added a MIT license. So feel free to do whatever you want :)

Sure I'd love to be listed. I'm currently located in Bangkok.

**Comment by PythonLinks** [comment]
Okay, I have added you.  We can change the text if you want. 
https://pythonlinks.info/map-of-open-source-python-projects

Tell your friends.

**Comment by xysun** [comment]
"Gangkok" is intentional or just a typo? :)
